<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="idoshoshani-lt" name="TestAttempt" tests="3" failures="3" timestamp="23 Nov 2017 17:07:49 GMT" time="144.393" errors="0">
  <testcase name="@AfterMethod tearDown" time="0.0" classname="com.myTests.NativeTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.experitest.client.Client.generateReport(Client.java:949)
	at com.myTests.NativeTest.tearDown(NativeTest.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="com.myTests.AppStoreTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.experitest.client.Client.getDeviceLog(Client.java:1095)
	at com.myTests.AppStoreTest.tearDown(AppStoreTest.java:110)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="testNativeLogin" time="30.427" classname="com.myTests.NativeTest">
    <failure type="com.experitest.client.InternalException" message="Exception caught while executing elementSendText: Element was not identified: &amp;apos;usernameTextField&amp;apos; at zone default">
      <![CDATA[com.experitest.client.InternalException: Exception caught while executing elementSendText: Element was not identified: 'usernameTextField' at zone default
	at com.experitest.client.JavaClientInternals.executeInternally(JavaClientInternals.java:249)
	at com.experitest.client.Client.execute(Client.java:247)
	at com.experitest.client.Client.elementSendText(Client.java:807)
	at com.myTests.NativeTest.testNativeLogin(NativeTest.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testNativeLogin -->
  <testcase name="OrderTest" time="48.274" classname="com.myTests.NativeTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.experitest.client.Client.hybridRunJavascript(Client.java:1376)
	at com.myTests.NativeTest.OrderTest(NativeTest.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- OrderTest -->
  <testcase name="test" time="64.728" classname="com.myTests.AppStoreTest">
    <failure type="com.experitest.client.InternalException" message="Exception caught while executing click: Element was not identified: &amp;apos;play_card&amp;apos; at zone default">
      <![CDATA[com.experitest.client.InternalException: Exception caught while executing click: Element was not identified: 'play_card' at zone default
	at com.experitest.client.JavaClientInternals.executeInternally(JavaClientInternals.java:249)
	at com.experitest.client.Client.execute(Client.java:247)
	at com.experitest.client.Client.click(Client.java:476)
	at com.myTests.AppStoreTest.test(AppStoreTest.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- TestAttempt -->
